# Generated by Django 5.0.7 on 2025-08-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0038_business_latitude_business_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_de_envio',
        ),
    ]
