# Generated by Django 5.0.7 on 2025-08-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0039_remove_producto_precio_de_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hace_delivery',
            field=models.BooleanField(default=True, help_text='Desmarque esta casilla si su negocio NO hace entregas a domicilio (solo retiro en sucursal)', verbose_name='¿Hace entregas a domicilio?'),
        ),
    ]
