# Generated by Django 5.0.7 on 2025-08-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0040_business_hace_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='hace_delivery',
        ),
        migrations.AddField(
            model_name='direcciondeenvio',
            name='nombre_huesped',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del huésped'),
        ),
        migrations.AddField(
            model_name='direcciondeenvio',
            name='numero_habitacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de habitación'),
        ),
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='opcion_entrega',
            field=models.CharField(choices=[('roomservice', 'Room Service - Entrega en habitación'), ('restaurante', 'Bajar al restaurante')], default='roomservice', max_length=100, verbose_name='¿Room Service o bajar al restaurante?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('efectivo', 'Efectivo al recibir'), ('habitacion', 'Cargo a habitación')], default='tarjeta', max_length=20, verbose_name='Método de pago'),
        ),
    ]
