# Generated by Django 5.0.7 on 2025-08-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0041_remove_business_hace_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='costo_envio',
        ),
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='direcciondeenvio',
            name='nombre_huesped',
        ),
    ]
